2016-06-04 23:38:27 - Inicio grabar detalles.
2016-06-04 23:38:27 - Hay 15798 contratos sin detalles.
2016-06-04 23:38:33 - Procesado expediente  10CO1013 id: 10191121
2016-06-04 23:38:40 - Procesado expediente  10CO1011 id: 10269136
2016-06-04 23:38:45 - Procesado expediente  10CO1015 id: 10445139
2016-06-04 23:39:02 - Error en expediente  10CO1017 id: 10693845
2016-06-04 23:39:02 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:39:07 - Procesado expediente  11CO0002 id: 11236835
2016-06-04 23:39:12 - Procesado expediente  10PN1003 id: 11656830
2016-06-04 23:39:17 - Procesado expediente  11PN0001 id: 11659866
2016-06-04 23:39:22 - Procesado expediente  10PN1004 id: 12846499
2016-06-04 23:39:27 - Procesado expediente  10PN1005 id: 13042011
2016-06-04 23:39:43 - Error en expediente  11PN0007 id: 13045026
2016-06-04 23:39:43 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:39:48 - Error en expediente  10PN1007 id: 13087355
2016-06-04 23:39:48 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:39:53 - Procesado expediente  10PN1008 id: 13087799
2016-06-04 23:40:10 - Error en expediente  11CO0004 id: 13268201
2016-06-04 23:40:10 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:40:15 - Procesado expediente  11PN0003 id: 13305430
2016-06-04 23:40:32 - Error en expediente  11CO0003 id: 13417649
2016-06-04 23:40:32 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:40:37 - Procesado expediente  11PN0005 id: 14784327
2016-06-04 23:40:42 - Procesado expediente  11PN0004 id: 15158040
2016-06-04 23:40:46 - Procesado expediente  10PN1006 id: 15747747
2016-06-04 23:40:51 - Procesado expediente  11PN0009 id: 15983006
2016-06-04 23:40:56 - Procesado expediente  11PN0006 id: 16937677
2016-06-04 23:41:01 - Procesado expediente  11PN0010 id: 16944627
2016-06-04 23:41:07 - Procesado expediente  12PN0002 id: 18914992
2016-06-04 23:41:12 - Procesado expediente  12PN0001 id: 20699279
2016-06-04 23:41:17 - Procesado expediente  12PN004 id: 22341557
2016-06-04 23:41:23 - Procesado expediente  12PN0004 id: 22578368
2016-06-04 23:41:29 - Procesado expediente  13CO0004 id: 23049411
2016-06-04 23:41:35 - Procesado expediente  13CO0001 id: 23064834
2016-06-04 23:41:41 - Error en expediente  13CO0003 id: 23295745
2016-06-04 23:41:41 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:41:48 - Procesado expediente  13CO0005 id: 23438822
2016-06-04 23:41:54 - Procesado expediente  12PN0003 id: 23441184
2016-06-04 23:42:09 - Error en expediente  13CO0002 id: 23891970
2016-06-04 23:42:09 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:42:15 - Procesado expediente  13CO0012 id: 25037569
2016-06-04 23:42:21 - Error en expediente  13CO0007 id: 25204818
2016-06-04 23:42:21 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:42:26 - Procesado expediente  13PN0003 id: 25256607
2016-06-04 23:42:34 - Error en expediente  13CO0011 id: 25434530
2016-06-04 23:42:34 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:42:39 - Procesado expediente  13PN0004 id: 27921772
2016-06-04 23:42:44 - Procesado expediente  13PN0005 id: 27922615
2016-06-04 23:42:51 - Procesado expediente  14CO0002 id: 28036701
2016-06-04 23:42:57 - Procesado expediente  14CO0003 id: 28072805
2016-06-04 23:43:03 - Error en expediente  14CO0004 id: 28075023
2016-06-04 23:43:03 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:43:09 - Procesado expediente  14PN0003 id: 29556341
2016-06-04 23:43:14 - Procesado expediente  14CO0008 id: 29985677
2016-06-04 23:43:20 - Error en expediente  15CO0009 id: 38484001
2016-06-04 23:43:20 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:43:37 - Error en expediente  15CO0015 id: 40928666
2016-06-04 23:43:37 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    fechadoc=datetime.strptime(row.find("td", {'class': 'fechaPubLeft'}).text, '%d/%m/%Y %H:%M:%S')
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:43:43 - Procesado expediente  2013/307PA001 id: 23080272
2016-06-04 23:43:48 - Procesado expediente  2013/307PN001 id: 23600854
2016-06-04 23:43:53 - Procesado expediente  2013/307PN006 id: 24328470
2016-06-04 23:43:58 - Procesado expediente  2013/307PA002 id: 24992695
2016-06-04 23:44:03 - Procesado expediente  307PN012 id: 25636549
2016-06-04 23:44:08 - Procesado expediente  2013/307PN007 id: 25716626
2016-06-04 23:44:14 - Procesado expediente  2013/307PN008 id: 25828879
2016-06-04 23:44:19 - Procesado expediente  2014/407PA001 id: 27600774
2016-06-04 23:44:25 - Procesado expediente  2014/407PN004 id: 28747001
2016-06-04 23:44:30 - Procesado expediente  2014/407PN007 id: 29576123
2016-06-04 23:44:49 - Error en expediente  2015/507PA006 id: 36421597
2016-06-04 23:44:49 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:44:56 - Error en expediente  2/227.06/11. id: 7078467
2016-06-04 23:44:56 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:45:03 - Procesado expediente  12/227.06/11 id: 8363067
2016-06-04 23:45:19 - Error en expediente  25/227.06/11 id: 9859690
2016-06-04 23:45:19 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:45:35 - Error en expediente  2011/010022201/001 id: 11178476
2016-06-04 23:45:35 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:45:41 - Error en expediente  2011/010022100/001 id: 13184158
2016-06-04 23:45:41 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:45:47 - Error en expediente  2011/0100227.06/027 id: 13849285
2016-06-04 23:45:47 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:46:03 - Error en expediente  2011/010022706/037 id: 15073284
2016-06-04 23:46:03 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:46:10 - Error en expediente  2012/22704/009. id: 21655751
2016-06-04 23:46:10 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:46:16 - Procesado expediente  2013/213/00008 id: 22589717
2016-06-04 23:46:23 - Procesado expediente  2013/22704/001 id: 22707278
2016-06-04 23:46:29 - Procesado expediente  2013/22106/005 id: 23103491
2016-06-04 23:46:35 - Procesado expediente  2013/630/00019 id: 26580996
2016-06-04 23:46:42 - Procesado expediente  2014/22706/023 id: 31076703
2016-06-04 23:46:59 - Error en expediente  PA 02/2012 id: 13118679
2016-06-04 23:46:59 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:47:04 - Error en expediente  PN 21/2012 id: 16033503
2016-06-04 23:47:04 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:47:12 - Procesado expediente  PN 23/2012 id: 16468568
2016-06-04 23:47:17 - Procesado expediente  PN 24/2012 id: 16470488
2016-06-04 23:47:23 - Procesado expediente  PA 02/2013 id: 19233287
2016-06-04 23:47:29 - Procesado expediente  PN 03/2013 id: 19279636
2016-06-04 23:47:34 - Procesado expediente  PN 04/2013 id: 19280919
2016-06-04 23:47:40 - Procesado expediente  PN 25/2013 id: 22703236
2016-06-04 23:47:46 - Procesado expediente  PN 28/2013 id: 23209048
2016-06-04 23:47:51 - Procesado expediente  PN 29/2013 id: 23675256
2016-06-04 23:47:57 - Error en expediente  PA 02/2014 id: 24233938
2016-06-04 23:47:57 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:03 - Error en expediente   PA 03/2014 id: 24367767
2016-06-04 23:48:03 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:11 - Error en expediente  PA 04/2014 id: 24369819
2016-06-04 23:48:11 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:17 - Error en expediente  25/2014 id: 26815517
2016-06-04 23:48:17 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:23 - Error en expediente  28/2014 id: 28057352
2016-06-04 23:48:23 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:32 - Error en expediente  02/2015 id: 30343382
2016-06-04 23:48:32 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:39 - Error en expediente  04/2015 id: 30344900
2016-06-04 23:48:39 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:45 - Error en expediente  05/2015 id: 30344954
2016-06-04 23:48:45 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:51 - Error en expediente  27/2015 id: 36693880
2016-06-04 23:48:51 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:48:57 - Error en expediente  02/2016 id: 41814764
2016-06-04 23:48:57 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:49:04 - Error en expediente  04/2016 id: 41818829
2016-06-04 23:49:04 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:49:11 - Error en expediente  26/2016 id: 50491774
2016-06-04 23:49:11 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:49:19 - Error en expediente  27/2016 id: 50500939
2016-06-04 23:49:19 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:49:23 - Procesado expediente  315/2010 id: 10428668
2016-06-04 23:49:29 - Procesado expediente  518/2011 id: 13252864
2016-06-04 23:49:34 - Error en expediente  335/2011 id: 13370688
2016-06-04 23:49:34 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:49:40 - Error en expediente  920/2011 id: 13549973
2016-06-04 23:49:40 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:49:46 - Error en expediente  516/2011 id: 14013040
2016-06-04 23:49:46 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:49:52 - Error en expediente  793/2011 id: 14082761
2016-06-04 23:49:52 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:49:58 - Error en expediente  928/2011 id: 14380848
2016-06-04 23:49:58 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:50:04 - Procesado expediente  1069/2011 id: 14394972
2016-06-04 23:50:11 - Procesado expediente  1089/2011 id: 14395616
2016-06-04 23:50:28 - Error en expediente  1170/2011 id: 15011552
2016-06-04 23:50:28 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:50:44 - Error en expediente  1147/2011 id: 15015111
2016-06-04 23:50:44 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:51:00 - Error en expediente  1420/2011 id: 15021648
2016-06-04 23:51:00 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:51:17 - Error en expediente  944/2011 id: 15024599
2016-06-04 23:51:17 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:51:33 - Error en expediente  1178/2011 id: 15075041
2016-06-04 23:51:33 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:51:50 - Error en expediente  933/2011 id: 15077660
2016-06-04 23:51:50 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:51:56 - Error en expediente  1190/2011 id: 15167033
2016-06-04 23:51:56 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:52:02 - Procesado expediente  1235/2011 id: 15777472
2016-06-04 23:52:08 - Procesado expediente  984/2011 id: 16637584
2016-06-04 23:52:14 - Procesado expediente  92/2012 id: 17262410
2016-06-04 23:52:20 - Procesado expediente  117/2012 id: 17338531
2016-06-04 23:52:28 - Error en expediente  548/2012 id: 17370453
2016-06-04 23:52:28 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:52:34 - Error en expediente  524/2011 id: 17586175
2016-06-04 23:52:34 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:52:41 - Error en expediente  2/2012 id: 17791058
2016-06-04 23:52:41 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:52:46 - Procesado expediente  217/2012 id: 18025880
2016-06-04 23:52:52 - Error en expediente  465/2012 id: 18060113
2016-06-04 23:52:52 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:53:10 - Error en expediente  615/2012 id: 18274780
2016-06-04 23:53:10 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:53:15 - Procesado expediente  139/2012 id: 18407420
2016-06-04 23:53:22 - Error en expediente  610/2012 id: 18677245
2016-06-04 23:53:22 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:53:27 - Procesado expediente  332/2012 id: 18783861
2016-06-04 23:53:33 - Procesado expediente  1/2012 id: 19198409
2016-06-04 23:53:39 - Error en expediente  484/2012 id: 19390802
2016-06-04 23:53:39 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:53:46 - Procesado expediente  638/2012 id: 19431521
2016-06-04 23:53:51 - Procesado expediente  639/2012 id: 19689412
2016-06-04 23:53:58 - Error en expediente  507/2012 id: 19820834
2016-06-04 23:53:58 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:54:05 - Error en expediente  843/2012 id: 20135100
2016-06-04 23:54:05 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:54:11 - Procesado expediente  824/2012 id: 20209200
2016-06-04 23:54:16 - Error en expediente  1022/2012 id: 20612208
2016-06-04 23:54:16 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:54:22 - Procesado expediente  463/2012 id: 20711014
2016-06-04 23:54:28 - Procesado expediente  774/2012 id: 20742752
2016-06-04 23:54:33 - Procesado expediente  593/2012 id: 20778155
2016-06-04 23:54:39 - Error en expediente  742/2012 id: 20898917
2016-06-04 23:54:39 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:54:45 - Procesado expediente  516/2012 id: 21512960
2016-06-04 23:54:51 - Procesado expediente  657/2012 id: 21528150
2016-06-04 23:54:56 - Procesado expediente  779/2012 id: 21532304
2016-06-04 23:55:04 - Procesado expediente  8/2013 id: 21930443
2016-06-04 23:55:11 - Error en expediente  9/2013 id: 22164897
2016-06-04 23:55:11 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:55:29 - Error en expediente  296/2013 id: 22283818
2016-06-04 23:55:29 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:55:34 - Procesado expediente  316/2013 id: 22551332
2016-06-04 23:55:41 - Error en expediente  420/2013 id: 22647168
2016-06-04 23:55:41 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:55:48 - Error en expediente  398/2013 id: 22702460
2016-06-04 23:55:48 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:55:55 - Error en expediente  450/2013 id: 22782507
2016-06-04 23:55:55 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:56:03 - Error en expediente  521/2013 id: 23026474
2016-06-04 23:56:03 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:56:10 - Error en expediente  374/2013 id: 23123267
2016-06-04 23:56:10 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:56:16 - Procesado expediente  429/2013 id: 23185862
2016-06-04 23:56:22 - Procesado expediente  422/2013 id: 23458726
2016-06-04 23:56:29 - Procesado expediente  318/2013 id: 23534935
2016-06-04 23:56:34 - Procesado expediente  519/2013 id: 23761558
2016-06-04 23:56:51 - Error en expediente  584/2013 id: 23819193
2016-06-04 23:56:51 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:56:57 - Error en expediente  604/2013 id: 23880581
2016-06-04 23:56:57 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:57:13 - Error en expediente  657/2013 id: 23896910
2016-06-04 23:57:13 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:57:20 - Procesado expediente  546/2013 id: 24111340
2016-06-04 23:57:26 - Procesado expediente  417/2013 id: 24187703
2016-06-04 23:57:31 - Procesado expediente  568/2013 id: 24308893
2016-06-04 23:57:37 - Error en expediente  716/2013 id: 24605241
2016-06-04 23:57:37 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:57:43 - Procesado expediente  690/2013 id: 24619799
2016-06-04 23:57:49 - Procesado expediente  800/2013 id: 25265921
2016-06-04 23:57:54 - Procesado expediente  680/2013 id: 25533778
2016-06-04 23:58:00 - Procesado expediente  804/2013 id: 25585123
2016-06-04 23:58:06 - Procesado expediente  675/2013 id: 25746588
2016-06-04 23:58:12 - Procesado expediente  715/2013 id: 25777385
2016-06-04 23:58:19 - Procesado expediente  882/2013 id: 25818050
2016-06-04 23:58:25 - Procesado expediente  898/2013 id: 25827043
2016-06-04 23:58:33 - Procesado expediente  964/2013 id: 26017267
2016-06-04 23:58:38 - Procesado expediente  736/2013 id: 26043297
2016-06-04 23:58:45 - Procesado expediente  952/2013 id: 26108228
2016-06-04 23:58:50 - Procesado expediente  953/2013 id: 26243744
2016-06-04 23:58:56 - Error en expediente  1036/2013 id: 26282246
2016-06-04 23:58:56 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:59:02 - Procesado expediente  1015/2013 id: 26325825
2016-06-04 23:59:07 - Procesado expediente  1025/2013 id: 26327104
2016-06-04 23:59:14 - Error en expediente  1134/2013 id: 26567195
2016-06-04 23:59:14 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:59:19 - Procesado expediente  801/2013 id: 26582321
2016-06-04 23:59:25 - Error en expediente  1149/2013 id: 26621623
2016-06-04 23:59:25 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:59:32 - Error en expediente  51/2014 id: 27146468
2016-06-04 23:59:32 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:59:38 - Error en expediente  29/2014 id: 27181287
2016-06-04 23:59:38 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:59:45 - Procesado expediente  50/2014 id: 27251630
2016-06-04 23:59:51 - Error en expediente  68/2014 id: 27254202
2016-06-04 23:59:51 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-04 23:59:57 - Error en expediente  31/2014 id: 27264390
2016-06-04 23:59:57 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:00:05 - Error en expediente  85/2014 id: 27282909
2016-06-05 00:00:05 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:00:12 - Procesado expediente  49/2014 id: 27527451
2016-06-05 00:00:20 - Procesado expediente  215/2014 id: 27552320
2016-06-05 00:00:27 - Error en expediente  249/2014 id: 27632055
2016-06-05 00:00:27 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:00:34 - Procesado expediente  240/2014 id: 27728661
2016-06-05 00:00:40 - Error en expediente  320/2014 id: 28042788
2016-06-05 00:00:40 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:00:47 - Error en expediente  368/2014 id: 28049404
2016-06-05 00:00:47 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:00:54 - Procesado expediente  308/2014 id: 28065247
2016-06-05 00:01:02 - Procesado expediente  234/2014 id: 28119005
2016-06-05 00:01:08 - Procesado expediente  272/2014 id: 28196464
2016-06-05 00:01:15 - Error en expediente  427/2014 id: 28301790
2016-06-05 00:01:15 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:01:32 - Error en expediente  403/2014 id: 28324784
2016-06-05 00:01:32 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:01:40 - Procesado expediente  280/2014 id: 28329633
2016-06-05 00:01:47 - Error en expediente  413/2014 id: 28347756
2016-06-05 00:01:47 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:02:06 - Error en expediente  309/2014 id: 28392553
2016-06-05 00:02:06 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:02:24 - Error en expediente  445/2014 id: 28562485
2016-06-05 00:02:24 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:02:31 - Procesado expediente  1047/2014 id: 28591651
2016-06-05 00:02:37 - Procesado expediente  288/2014 id: 28728331
2016-06-05 00:02:44 - Procesado expediente  97/2014 id: 28815286
2016-06-05 00:02:50 - Procesado expediente  324/2014 id: 28924749
2016-06-05 00:02:55 - Procesado expediente  319/2014 id: 28928750
2016-06-05 00:03:03 - Procesado expediente  306/2014 id: 28931172
2016-06-05 00:03:10 - Procesado expediente  371/2014 id: 28947075
2016-06-05 00:03:16 - Error en expediente  285/2014 id: 28973784
2016-06-05 00:03:16 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:03:23 - Procesado expediente  226/2014 id: 29010903
2016-06-05 00:03:29 - Procesado expediente  213/2014 id: 29027831
2016-06-05 00:03:35 - Procesado expediente  212/2014 id: 29070411
2016-06-05 00:03:41 - Procesado expediente  211/2014 id: 29697812
2016-06-05 00:03:48 - Procesado expediente  503/2014 id: 29815275
2016-06-05 00:03:54 - Procesado expediente  378/2014 id: 29895441
2016-06-05 00:04:01 - Error en expediente  676/2014 id: 29949108
2016-06-05 00:04:01 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:04:10 - Error en expediente  702/2014 id: 29972145
2016-06-05 00:04:10 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:04:29 - Error en expediente  715/2014 id: 29978374
2016-06-05 00:04:29 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:04:36 - Procesado expediente  209/2014 id: 30002483
2016-06-05 00:04:43 - Procesado expediente  422/2014 id: 30038248
2016-06-05 00:04:49 - Procesado expediente  373/2014 id: 30133863
2016-06-05 00:05:08 - Error en expediente  757/2014 id: 30471795
2016-06-05 00:05:08 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:05:28 - Error en expediente  753/2014 id: 30486736
2016-06-05 00:05:28 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:05:36 - Error en expediente  615/2014 id: 30508285
2016-06-05 00:05:36 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:05:44 - Error en expediente  845/2014 id: 31042446
2016-06-05 00:05:44 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:05:52 - Error en expediente  846/2014 id: 31827736
2016-06-05 00:05:52 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:05:59 - Error en expediente  1029/2014 id: 33456227
2016-06-05 00:05:59 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:06:08 - Error en expediente  1006/2014 id: 34008703
2016-06-05 00:06:08 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:06:18 - Error en expediente  1132/2014 id: 34954216
2016-06-05 00:06:18 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:06:27 - Error en expediente  300/2015 id: 37255841
2016-06-05 00:06:27 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:06:34 - Error en expediente  316/2015 id: 37851069
2016-06-05 00:06:34 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:06:53 - Error en expediente  385/2015 id: 37885304
2016-06-05 00:06:53 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:07:01 - Error en expediente  356/2015 id: 38080359
2016-06-05 00:07:01 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:07:21 - Error en expediente  369/2015 id: 38334657
2016-06-05 00:07:21 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:07:30 - Error en expediente  288/2015 id: 40309440
2016-06-05 00:07:30 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:07:36 - Error en expediente  304/2015 id: 41429505
2016-06-05 00:07:36 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:07:45 - Error en expediente  692/2015 id: 41448844
2016-06-05 00:07:45 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:07:52 - Error en expediente  694/2015 id: 41610905
2016-06-05 00:07:52 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:08:00 - Procesado expediente  675/2015 id: 41623895
2016-06-05 00:08:21 - Error en expediente  319/2015 id: 41685406
2016-06-05 00:08:21 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:08:28 - Error en expediente  852/2015 id: 43812626
2016-06-05 00:08:28 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:08:46 - Error en expediente  859/2015 id: 43837227
2016-06-05 00:08:46 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:08:55 - Error en expediente  787/2015 id: 46168533
2016-06-05 00:08:55 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:09:04 - Error en expediente  4/2016 id: 49204736
2016-06-05 00:09:04 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:09:22 - Error en expediente  1160/2015 id: 50252674
2016-06-05 00:09:22 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:09:30 - Error en expediente  1/2016 id: 50568211
2016-06-05 00:09:30 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:09:49 - Error en expediente  1161/2015 id: 50689695
2016-06-05 00:09:49 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:09:56 - Error en expediente  1154/2015 id: 51039157
2016-06-05 00:09:56 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:10:02 - Error en expediente  414/2016 id: 51311373
2016-06-05 00:10:02 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:10:09 - Error en expediente  1155/2015 id: 51428317
2016-06-05 00:10:09 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:10:26 - Error en expediente  380/2016 id: 51497779
2016-06-05 00:10:26 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:10:44 - Error en expediente  403/2016 id: 52175061
2016-06-05 00:10:44 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:11:00 - Procesado expediente  3/2016 id: 52396689
2016-06-05 00:11:17 - Error en expediente  19/227.06/11 id: 8910530
2016-06-05 00:11:17 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:11:35 - Error en expediente  2011/010022706/022 id: 13103344
2016-06-05 00:11:35 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:11:57 - Error en expediente  2011/0100630/00014 id: 13184428
2016-06-05 00:11:57 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:12:05 - Error en expediente  2011/010022100/002 id: 15073167
2016-06-05 00:12:05 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:12:15 - Error en expediente  2011/0100227.06/038 id: 15478208
2016-06-05 00:12:15 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:12:24 - Error en expediente  2012/010022706/045 id: 17060768
2016-06-05 00:12:24 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:12:36 - Error en expediente  2013/22201/001 id: 21819722
2016-06-05 00:12:36 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:12:46 - Procesado expediente  2013/22706/012 id: 22896351
2016-06-05 00:13:00 - Error en expediente  2013/22706/034 id: 25380716
2016-06-05 00:13:00 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 81, in extraeDetalles
    self.driver.find_element_by_id('viewns_Z7_AVEQAI930OBRD02JPMTPG21004_:form1:enlaceExpediente_0').click() #sólo sirve para el primer expediente... como es este caso.
  File "/home/jmartinz/00.py/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 74, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/jmartinz/00.py/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 457, in _execute
    return self._parent.execute(command, params)
  File "/home/jmartinz/00.py/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "/home/jmartinz/00.py/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: {"errorMessage":"Click failed: timeout","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"81","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:44420","User-Agent":"Python-urllib/3.5"},"httpVersion":"1.1","method":"POST","post":"{\"sessionId\": \"78291b80-2aa1-11e6-b6b7-dd967ce2c374\", \"id\": \":wdc:1465078370001\"}","url":"/click","urlParsed":{"anchor":"","query":"","file":"click","directory":"/","path":"/click","relative":"/click","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/click","queryKey":{},"chunks":["click"]},"urlOriginal":"/session/78291b80-2aa1-11e6-b6b7-dd967ce2c374/element/%3Awdc%3A1465078370001/click"}}
Screenshot: available via screen


2016-06-05 00:13:09 - Procesado expediente  2013/22700/009 id: 25970789
2016-06-05 00:13:19 - Error en expediente  2015/22706/001 id: 34743833
2016-06-05 00:13:19 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:13:26 - Procesado expediente  16/2011 id: 9414801
2016-06-05 00:13:33 - Procesado expediente  28/2011 id: 9940422
2016-06-05 00:13:52 - Error en expediente  48/2011 id: 10941643
2016-06-05 00:13:52 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:14:02 - Error en expediente  9/2012 id: 13294168
2016-06-05 00:14:02 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:14:09 - Procesado expediente  12/2012 id: 13397174
2016-06-05 00:14:15 - Procesado expediente  20/2012 id: 13863201
2016-06-05 00:14:21 - Error en expediente  51/2012 id: 17173726
2016-06-05 00:14:21 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:14:28 - Error en expediente  49/2012 id: 17175966
2016-06-05 00:14:28 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:14:34 - Procesado expediente  52/2012 id: 17177306
2016-06-05 00:14:42 - Error en expediente  9/2013 id: 19105322
2016-06-05 00:14:42 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:14:50 - Error en expediente  5/2013 id: 19129022
2016-06-05 00:14:50 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:14:56 - Procesado expediente  78/2012 id: 19493535
2016-06-05 00:15:04 - Error en expediente  32/2013 id: 23338541
2016-06-05 00:15:04 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:15:11 - Error en expediente  33/2013 id: 23449912
2016-06-05 00:15:11 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:15:18 - Error en expediente  34/2013 id: 23451908
2016-06-05 00:15:18 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:15:23 - Error en expediente  39/2013 id: 23456185
2016-06-05 00:15:23 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:15:29 - Error en expediente  35/2013 id: 23460119
2016-06-05 00:15:29 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:15:36 - Error en expediente  61/2013 id: 24458735
2016-06-05 00:15:36 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:15:44 - Error en expediente  86/2014 id: 32273321
2016-06-05 00:15:44 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:15:53 - Error en expediente  18/2015 id: 36983542
2016-06-05 00:15:53 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:16:02 - Error en expediente  1/2016 id: 43002342
2016-06-05 00:16:02 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:16:11 - Error en expediente  3/2016 id: 43856368
2016-06-05 00:16:11 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:16:18 - Procesado expediente  20110017 id: 12014947
2016-06-05 00:16:37 - Error en expediente  20110479 id: 12751703
2016-06-05 00:16:37 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:16:43 - Procesado expediente  20110425 id: 13934421
2016-06-05 00:16:50 - Procesado expediente  2012/20PN003 id: 16983801
2016-06-05 00:16:56 - Procesado expediente  2012/01PN002 id: 16997204
2016-06-05 00:17:03 - Procesado expediente  2012/20PN022 id: 17544514
2016-06-05 00:17:10 - Procesado expediente  2012020PN020 id: 17653729
2016-06-05 00:17:18 - Procesado expediente  2012010001PA006 id: 17678995
2016-06-05 00:17:24 - Procesado expediente  2012/01PA004 id: 17695667
2016-06-05 00:17:31 - Procesado expediente  2012/07PN001 id: 17943415
2016-06-05 00:17:37 - Procesado expediente  2012/20PN009 id: 17997996
2016-06-05 00:17:43 - Procesado expediente  2012/20PN006 id: 18028289
2016-06-05 00:17:49 - Procesado expediente  2012/07PN002 id: 18064981
2016-06-05 00:17:55 - Procesado expediente  2012/01PA005 id: 18097444
2016-06-05 00:18:02 - Procesado expediente  2012/20PN021 id: 18131652
2016-06-05 00:18:09 - Procesado expediente  2012/20PN014 id: 18173595
2016-06-05 00:18:15 - Procesado expediente  2012/20PN007 id: 18252531
2016-06-05 00:18:22 - Procesado expediente  01PN009 id: 18287746
2016-06-05 00:18:28 - Procesado expediente  20PN013 id: 18307084
2016-06-05 00:18:35 - Procesado expediente  2012/20PN011 id: 18490021
2016-06-05 00:18:41 - Procesado expediente  2012/20PN017 id: 18506152
2016-06-05 00:18:48 - Procesado expediente  2012/AC002 id: 18511643
2016-06-05 00:18:55 - Procesado expediente  2012/20PN024 id: 18721623
2016-06-05 00:19:01 - Procesado expediente  2012/22PN002 id: 18889208
2016-06-05 00:19:07 - Procesado expediente  2012/20PN015 id: 19015990
2016-06-05 00:19:14 - Procesado expediente  2012/20PN016 id: 19215469
2016-06-05 00:19:20 - Procesado expediente  01PN019 id: 19245235
2016-06-05 00:19:27 - Procesado expediente  201201PN003 id: 19261292
2016-06-05 00:19:44 - Error en expediente  2012/AC002M id: 19310333
2016-06-05 00:19:44 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:19:52 - Error en expediente  2012/01PA008 id: 19382042
2016-06-05 00:19:52 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:20:01 - Procesado expediente  2012/01PN021 id: 19488309
2016-06-05 00:20:10 - Procesado expediente  2012/01PN020 id: 19625771
2016-06-05 00:20:16 - Procesado expediente  2012/09CB001 id: 19715044
2016-06-05 00:20:23 - Procesado expediente  2012/01PN036 id: 20136669
2016-06-05 00:20:30 - Procesado expediente  2012/01PN013 id: 20187954
2016-06-05 00:20:35 - Procesado expediente  2012/01PN016 id: 20188296
2016-06-05 00:20:41 - Procesado expediente  2012/01PN017 id: 20188583
2016-06-05 00:20:47 - Error en expediente  2012/07PN003 id: 20312910
2016-06-05 00:20:47 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:20:55 - Procesado expediente  2012/01PN035 id: 20326878
2016-06-05 00:21:01 - Procesado expediente  2012/01PN033 id: 20327794
2016-06-05 00:21:07 - Procesado expediente  2012/01PN027 id: 20342159
2016-06-05 00:21:13 - Procesado expediente  2012/01PN029 id: 20344075
2016-06-05 00:21:19 - Procesado expediente  2012/01PN028 id: 20453108
2016-06-05 00:21:26 - Procesado expediente  2012/07PN005 id: 20500361
2016-06-05 00:21:32 - Procesado expediente  2012/01PN037 id: 20515379
2016-06-05 00:21:38 - Procesado expediente  2012/01PN038 id: 20522002
2016-06-05 00:21:44 - Procesado expediente  2012/01PN039 id: 20591029
2016-06-05 00:21:50 - Procesado expediente  2012/07PN004 id: 20637590
2016-06-05 00:21:56 - Procesado expediente  2012/01PN040 id: 20830164
2016-06-05 00:22:02 - Procesado expediente  2012/01PN041 id: 21172859
2016-06-05 00:22:09 - Procesado expediente  12PN002 id: 21318682
2016-06-05 00:22:15 - Procesado expediente  2012/01PN044 id: 21439598
2016-06-05 00:22:22 - Procesado expediente  2012/01PN043 id: 21442021
2016-06-05 00:22:28 - Procesado expediente  2012/01PN045 id: 21558518
2016-06-05 00:22:34 - Procesado expediente  2013/21PN001 id: 21989303
2016-06-05 00:22:41 - Procesado expediente  2013-FOR/ABIERTO/001  id: 22234312
2016-06-05 00:22:48 - Procesado expediente  2013/301PA005 id: 22578536
2016-06-05 00:22:55 - Procesado expediente  2013/321PA001 id: 22662190
2016-06-05 00:23:02 - Procesado expediente  2013/301PN015 id: 22852813
2016-06-05 00:23:09 - Procesado expediente  2013/301PN008 id: 22913577
2016-06-05 00:23:20 - Error en expediente  2013/301PA001 id: 22954527
2016-06-05 00:23:20 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:23:27 - Procesado expediente  2013/301PN010 id: 23073369
2016-06-05 00:23:34 - Procesado expediente  2013/301PN018 id: 23252970
2016-06-05 00:23:40 - Procesado expediente  2013/01PN014 id: 23262190
2016-06-05 00:23:46 - Procesado expediente  2013/301PN017 id: 23318529
2016-06-05 00:23:52 - Procesado expediente  2013/01PN003 id: 23336391
2016-06-05 00:23:59 - Procesado expediente  2013/01PA007 id: 23585438
2016-06-05 00:24:05 - Procesado expediente  2013/301PN019 id: 24108387
2016-06-05 00:24:12 - Procesado expediente  2013/01PA003 id: 24308198
2016-06-05 00:24:19 - Procesado expediente  2013/301PN016 id: 24387302
2016-06-05 00:24:26 - Procesado expediente  2013/301PA009 id: 24552718
2016-06-05 00:24:32 - Procesado expediente  2013/302PN001 id: 24763890
2016-06-05 00:24:38 - Procesado expediente  2013/301PN023 id: 24852624
2016-06-05 00:24:45 - Procesado expediente  2013/301PN026 id: 25233319
2016-06-05 00:24:52 - Procesado expediente  2013/301PN025 id: 25267914
2016-06-05 00:24:58 - Procesado expediente  2013/301PN021 id: 25370166
2016-06-05 00:25:05 - Procesado expediente  2013/301PN022 id: 25399295
2016-06-05 00:25:11 - Procesado expediente  2013/301PN024 id: 25525890
2016-06-05 00:25:18 - Procesado expediente  2013/01PN005 id: 25664508
2016-06-05 00:25:25 - Procesado expediente  2013/301PN029 id: 25830012
2016-06-05 00:25:31 - Procesado expediente  2013/301PN030 id: 25917487
2016-06-05 00:25:38 - Procesado expediente  2014/401PN002 id: 27857710
2016-06-05 00:25:44 - Procesado expediente  2014/401PN005 id: 28429765
2016-06-05 00:25:51 - Procesado expediente  2014/401PN007 id: 28562412
2016-06-05 00:25:57 - Procesado expediente  2014/401PN009 id: 28563370
2016-06-05 00:26:05 - Procesado expediente  2014/401PN003 id: 28661955
2016-06-05 00:26:12 - Procesado expediente  2014/401PN004 id: 28668195
2016-06-05 00:26:19 - Procesado expediente  2014/401PN013 id: 28698692
2016-06-05 00:26:25 - Procesado expediente  2014/401PN006 id: 28710631
2016-06-05 00:26:32 - Procesado expediente  2014/401PN001 id: 28779216
2016-06-05 00:26:39 - Procesado expediente  2014/401PN012 id: 29112663
2016-06-05 00:26:46 - Procesado expediente  2014/401PN021 id: 29543766
2016-06-05 00:26:52 - Procesado expediente  2014/401PN018 id: 29544993
2016-06-05 00:26:59 - Procesado expediente  2014/401PN017 id: 29546902
2016-06-05 00:27:05 - Procesado expediente  2014/401PN019 id: 29548372
2016-06-05 00:27:11 - Procesado expediente  2014/401PN020 id: 29557403
2016-06-05 00:27:17 - Procesado expediente  2014/401PN026 id: 30335803
2016-06-05 00:27:37 - Error en expediente  2015/501PA001 id: 35256736
2016-06-05 00:27:37 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:27:42 - Procesado expediente  PN 10/113 id: 9019614
2016-06-05 00:28:00 - Error en expediente  CA 11/019 id: 10627308
2016-06-05 00:28:00 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:28:18 - Error en expediente  CA 11/001 id: 10774618
2016-06-05 00:28:18 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:28:24 - Error en expediente  CA 11/046 id: 11667163
2016-06-05 00:28:24 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:28:42 - Error en expediente  Ca 11/047 id: 12140215
2016-06-05 00:28:42 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:28:59 - Error en expediente  CA 11/056 id: 12469540
2016-06-05 00:28:59 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:29:17 - Error en expediente  CA 11/005 id: 12803214
2016-06-05 00:29:17 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:29:34 - Error en expediente  CA 11/068 id: 12982862
2016-06-05 00:29:34 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:29:51 - Error en expediente  CA 11/051 id: 13109059
2016-06-05 00:29:51 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:29:58 - Procesado expediente  PN 11/126 id: 15004332
2016-06-05 00:30:06 - Procesado expediente  PN 11/160 id: 15615530
2016-06-05 00:30:13 - Error en expediente  CA 12/002 id: 15960012
2016-06-05 00:30:13 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:30:19 - Procesado expediente  PN 12/012 id: 16999375
2016-06-05 00:30:26 - Procesado expediente  PN 12/008 id: 17248550
2016-06-05 00:30:32 - Procesado expediente  PN 12/024 id: 17650515
2016-06-05 00:30:40 - Error en expediente  CA 12/023 id: 17693590
2016-06-05 00:30:40 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:30:46 - Procesado expediente  PN 12/014 id: 18043154
2016-06-05 00:30:52 - Procesado expediente  PN 12/032 id: 18276166
2016-06-05 00:31:10 - Error en expediente  PA 12/026 id: 18377672
2016-06-05 00:31:10 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:31:27 - Error en expediente  CA 12/050 id: 19186880
2016-06-05 00:31:27 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:31:34 - Procesado expediente  12/058 id: 19281454
2016-06-05 00:31:40 - Procesado expediente  PN 12/059 id: 19447374
2016-06-05 00:31:47 - Error en expediente  CA 12/071 id: 20295886
2016-06-05 00:31:47 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:32:05 - Error en expediente  13/009 id: 21942660
2016-06-05 00:32:05 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:32:22 - Error en expediente  13/008 id: 21945379
2016-06-05 00:32:22 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:32:29 - Error en expediente  13/017 id: 22575576
2016-06-05 00:32:29 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:32:36 - Procesado expediente  PN 13/006 id: 22691093
2016-06-05 00:32:44 - Error en expediente  13/011 id: 22724612
2016-06-05 00:32:44 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:32:50 - Procesado expediente  PN 13/026 id: 22725124
2016-06-05 00:32:57 - Procesado expediente  PN 13/036 id: 22736969
2016-06-05 00:33:04 - Error en expediente  CA 13/059 id: 23094963
2016-06-05 00:33:04 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:33:11 - Procesado expediente  PN 13/055 id: 23126002
2016-06-05 00:33:18 - Procesado expediente  PN 13/053 id: 23205671
2016-06-05 00:33:25 - Procesado expediente  PN 13/054 id: 23572896
2016-06-05 00:33:43 - Error en expediente  13/071 id: 23647831
2016-06-05 00:33:43 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:33:50 - Error en expediente  13/089 id: 24228426
2016-06-05 00:33:50 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:33:57 - Procesado expediente  13/085 id: 24253689
2016-06-05 00:34:06 - Error en expediente  13/086 id: 24438526
2016-06-05 00:34:06 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:34:15 - Procesado expediente  PN 13/094 id: 24542500
2016-06-05 00:34:22 - Procesado expediente  13/087 id: 24702279
2016-06-05 00:34:29 - Procesado expediente  2013/200OGA id: 24855865
2016-06-05 00:34:36 - Error en expediente  13/096 id: 25126675
2016-06-05 00:34:36 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:34:43 - Procesado expediente  13/098 id: 25652275
2016-06-05 00:35:05 - Error en expediente  AM 2013/161 id: 26192539
2016-06-05 00:35:05 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:35:14 - Error en expediente  13/123 id: 26236640
2016-06-05 00:35:14 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:35:20 - Procesado expediente  PN 13/108 id: 26344793
2016-06-05 00:35:27 - Procesado expediente  PN 13/152 id: 26922434
2016-06-05 00:35:36 - Error en expediente  13/175 id: 26926934
2016-06-05 00:35:36 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:35:42 - Procesado expediente  PN 2014/015 id: 28061977
2016-06-05 00:35:50 - Procesado expediente  PN 14/029 id: 28455801
2016-06-05 00:35:57 - Error en expediente  CA 14/064 id: 28624424
2016-06-05 00:35:57 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:36:05 - Procesado expediente  PN 14/016 id: 28743612
2016-06-05 00:36:12 - Procesado expediente  PN 14/044 id: 28971300
2016-06-05 00:36:19 - Procesado expediente  PN 14/036 id: 28971408
2016-06-05 00:36:27 - Procesado expediente  PN 2014/010 id: 29129641
2016-06-05 00:36:35 - Procesado expediente  PN 2014/006 id: 29366784
2016-06-05 00:36:42 - Procesado expediente  PN 2014/028 id: 29620734
2016-06-05 00:36:49 - Procesado expediente  2014/100OGA id: 30433684
2016-06-05 00:37:10 - Error en expediente  AM 14/164 id: 33591776
2016-06-05 00:37:10 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:37:20 - Error en expediente  2015/009 id: 34790495
2016-06-05 00:37:20 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:37:28 - Error en expediente  PA 15/008 id: 36638865
2016-06-05 00:37:28 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:37:35 - Error en expediente  P.A. 15/011 id: 39671238
2016-06-05 00:37:35 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:37:43 - Error en expediente  PA 2015/142 id: 41069241
2016-06-05 00:37:43 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:37:52 - Error en expediente  PA 2015//073 id: 41142098
2016-06-05 00:37:52 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:38:13 - Error en expediente  AM 2015/171 id: 41712788
2016-06-05 00:38:13 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:38:33 - Error en expediente  AM 2015/172 id: 41721676
2016-06-05 00:38:33 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:38:51 - Error en expediente  AM 2015/204 id: 43984090
2016-06-05 00:38:51 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:39:10 - Error en expediente  AM 2015/206 id: 43999912
2016-06-05 00:39:10 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:39:17 - Error en expediente  PA 2015/259 id: 46934764
2016-06-05 00:39:17 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:39:33 - Error en expediente  2016/049 id: 51120263
2016-06-05 00:39:33 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

2016-06-05 00:39:50 - Error en expediente  2016/050 id: 51127579
2016-06-05 00:39:50 - Error inesperadoTraceback (most recent call last):
  File "pce_grabar_detalles.py", line 98, in main
    detalles=detalleContrato(numExpediente = contrato.num_expediente, OrgContratacion=contrato.descripcion, driverType=2)
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 45, in __init__
    self.extraeDetalles()
  File "/home/jmartinz/00.py/pyCrawler/10.contratacionE/pce_extrae_detalle_contrato.py", line 118, in extraeDetalles
    try:
AttributeError: 'NoneType' object has no attribute 'text'

